# Generated by Django 5.1.5 on 2025-02-05 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_repository_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='repository',
            name='token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.CharField(choices=[('GitHub', 'GitHub'), ('GitLab', 'GitLab'), ('Bitbucket', 'Bitbucket')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='type',
            field=models.CharField(choices=[('GitHub', 'GitHub'), ('GitLab', 'GitLab'), ('Jira', 'Jira')], max_length=20),
        ),
    ]
